### ISSUE TITLE
会不会考虑支持多模态模型

### ISSUE THREAD

**Issue by ehlxr** [shell-nlp/gpt_server#11]
会不会考虑支持多模态模型，比如 glm-4v-9b

**Comment by shell-nlp** [comment]
考虑支持，暂时没时间做

**Comment by shell-nlp** [comment]
> 会不会考虑支持多模态模型，比如 glm-4v-9b

支持了 glm-4v-9b 的 lmdeploy-pytorch 后端，欢迎体验 测试

**Comment by shell-nlp** [comment]
后面有时间会继续完善其它 多模态模型，优先支持 中文、VLM榜单靠前、口碑好的模型

**Comment by shell-nlp** [comment]
使用样例代码： https://github.com/shell-nlp/gpt_server/blob/main/tests/test_openai_vl_chat.py

**Comment by shell-nlp** [comment]
今晚我看一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月22日(周一) 下午5:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [shell-nlp/gpt_server] 会不会考虑支持多模态模型 (Issue #11)




 
大佬，报错了image.png (view on web)

**Comment by shell-nlp** [comment]
> 大佬，报错了 使用 pip install -r requirements-dev.txt --no-deps 安装的依赖
> 
> ![image](https://private-user-images.githubusercontent.com/11313370/350907581-6f42f57b-ac24-4d24-99ab-3bb2b5d2df86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NjI4OTEsIm5iZiI6MTcyMTY2MjU5MSwicGF0aCI6Ii8xMTMxMzM3MC8zNTA5MDc1ODEtNmY0MmY1N2ItYWMyNC00ZDI0LTk5YWItM2JiMmI1ZDJkZjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE1MzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMDJhZTU1ZGRmM2QyM2E2OTIzZmU0ZmQ5NTI3NTA5NjlhY2ZlMzliNGY0MWU4ZTA2NTk5NzFiYTE3OWYyMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t0QsYfi7rnWgyAF-OCQlvzaCNilPk1NDXiFiOAUSj24)

我这里测试是正常的，我看了代码， 你这里报错是由于控制器没有注册上，
![image](https://github.com/user-attachments/assets/3b4f5261-5163-4f49-a3f5-71512c3af536)
你看一下你的日志，控制器 是否启动正常

**Comment by shell-nlp** [comment]
![image](https://github.com/user-attachments/assets/3d584f25-86bc-462d-b894-224ef9b31dfa)
看日志是没有问题的，你可以加我 微信

**Comment by shell-nlp** [comment]
如果问题已解决请关闭 issue
