### ISSUE TITLE
依赖好多

### ISSUE THREAD

**Issue by pc-mysql** [shell-nlp/gpt_server#12]
感觉仓库的依赖好多啊，下的时间太长了 ，可以精简一下嘛

**Comment by shell-nlp** [comment]
> 感觉仓库的依赖好多啊，下的时间太长了 ，可以精简一下嘛

其实仓库需要的库仅有 fastchat torch vllm lmdeploy sentencetransformer 这几个库，只不过这五个库 它们依赖了很多第三方库，我导出依赖的时候，把它们全部导出了，如果感觉看着太多的话，后面完全可以简化成 五个库
