### ISSUE TITLE
[請教] response_format相關實現

### ISSUE THREAD

**Issue by milk333445** [shell-nlp/gpt_server#17]
想請問大佬，剛好最近也在開發本地模型的openai接口，請問response_format這個參數是只要單純處理模型輸出(parse成不同形式返回用戶)，還是也要再輸入加入類似tool的prompt呢? 謝謝!

**Comment by shell-nlp** [comment]
这个功能暂时还未实现， 但是据我了解， 是要再加入类似 tool的一个Scheme

**Comment by shell-nlp** [comment]
vllm 和 lmdeploy 都已经实现了这个功能， 你可以先看一下他们的官网文档， 后面有时间 我将会引入这个功能

**Comment by milk333445** [comment]
我有看過vllm的源碼，他們的實現我的理解是不會對輸入做修改(就是不是類似tool還要對system prompt做修改)，只是單純在request的format加一個optional的response_format，然後對輸出做parse，把對應的format抓出來，根據格式返回給用戶，不知道這樣理解對不對，感謝交流!

**Comment by shell-nlp** [comment]
我的理解(不一定正确，因为我也是了解了一点)：  这样理解不完全正确， response_format表示输出要严格按照 、规定的json格式输出，prompt 中的格式规定并不能完全保证大模型一定会按照json格式输出，要想大模型一定会输出规定的json格式，就必须对大模型的Decoder(解码)过程进行限制(就比如 beam search的搜索空间中，强制要求输出必须是 规定的json格式)

**Comment by shell-nlp** [comment]
response_format 实现， 现在 vllm 后端已经支持了， 可以尝试以下，某些模型仍然支持不是太好
