### ISSUE TITLE
glm4-9b模型在lmdeploy-turbo下推理文不对题

### ISSUE THREAD

**Issue by echohsq** [shell-nlp/gpt_server#21]
glm4-9b模型在lmdeploy-turbo下推理时会不根据提问内容进行回答，问什么都会输出一大堆无关内容

**Comment by shell-nlp** [comment]
已修复，请拉取最新代码

**Comment by shell-nlp** [comment]
> glm4-9b模型在lmdeploy-turbo下推理时会不根据提问内容进行回答，问什么都会输出一大堆无关内容

已修复，请拉取最新代码
