### ISSUE TITLE
能不能调整下rerank的接口调用方式

### ISSUE THREAD

**Issue by swy0915** [shell-nlp/gpt_server#25]
能不能调整下rerank的接口调用方式，可以参考xinference，因为现在的rerank不能兼容一些其他工具例如dify

**Comment by shell-nlp** [comment]
好，我研究一下

**Comment by shell-nlp** [comment]
> 能不能调整下rerank的接口调用方式，可以参考xinference，因为现在的rerank不能兼容一些其他工具例如dify

已实现 请测试    https://github.com/shell-nlp/gpt_server/blob/main/tests/test_rerank.py

**Comment by shell-nlp** [comment]
麻烦测试一下，反馈一下 是否可以在 dify 中 正常使用

**Comment by swy0915** [comment]
> 麻烦测试一下，反馈一下 是否可以在 dify 中 正常使用

测试过了 可以用

**Comment by shell-nlp** [comment]
ok
