### ISSUE TITLE
接口没有和OpenAI标准对接好

### ISSUE THREAD

**Issue by DazeCat** [shell-nlp/gpt_server#26]
接口没有和OpenAI包对接好，请求参数和返回的参数格式都不一样。

**Comment by shell-nlp** [comment]
具体是哪个部分， 很多用户已经使用OpenAI 库正常运行很久了

**Comment by shell-nlp** [comment]
请排查 openai==1.55.0   是否正确

**Comment by shell-nlp** [comment]
请排查 openai 版本 "openai==1.55.3

**Comment by shell-nlp** [comment]
> 接口没有和OpenAI包对接好，请求参数和返回的参数格式都不一样。

具体是哪个部分， 很多用户已经使用OpenAI 库正常运行很久了
请排查 openai 版本 "openai==1.55.3

**Comment by DazeCat** [comment]
找到了 是我的问题，调用的worker的api，8022的api接口没有问题

**Comment by shell-nlp** [comment]
> 找到了 是我的问题，调用的worker的api，8022的api接口没有问题

好的，感谢使用本项目， 目前项目没有太好的文档，确实会存在使用错误的问题
