### ISSUE TITLE
在windows下执行异常

### ISSUE THREAD

**Issue by firstjack** [shell-nlp/gpt_server#3]
请问是不支持windows吗？用conda建立一个新环境并执行python main.py后提示如下
The "freeze_support()" line can be omitted if the program  is not going to be frozen to produce an executable.

**Comment by shell-nlp** [comment]
windons 我没有测试过， 你可以使用 windows 自带的 WSL ，WSL我是测试过的，

**Comment by shell-nlp** [comment]
> 请问是不支持windows吗？用conda建立一个新环境并执行python main.py后提示如下 The "freeze_support()" line can be omitted if the program is not going to be frozen to produce an executable.

我测试下试试

**Comment by shell-nlp** [comment]
> 请问是不支持windows吗？用conda建立一个新环境并执行python main.py后提示如下 The "freeze_support()" line can be omitted if the program is not going to be frozen to produce an executable.

https://blog.csdn.net/shenfuli/article/details/103969964 这是我查到了 Windows的解决办法， 你试一下 可行吗

**Comment by firstjack** [comment]
换到linux下执行不报错了，就是这个还能支持纯cpu运行吗？谢谢

**Comment by shell-nlp** [comment]
> 换到linux下执行不报错了，就是这个还能支持纯cpu运行吗？谢谢

代码会自动检测 使用 cpu 还是gpu 不过cpu推理大模型就太慢了

**Comment by firstjack** [comment]
目前我想只把embedding用cpu来跑，不过api跑起来了，但又提示没有GPU驱动，是否在yaml文件中还有其它的设置呢？感谢
 RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
 我现在的配置如下
   - acge_text_embedding:
      alias: null # 别名   
      enable: true  # false true
      model_name_or_path: /home/embegdding/acge_text_embedding
      model_type: embedding
      work_mode: hf

      workers:
      - gpus:
        - 0

**Comment by shell-nlp** [comment]
> 目前我想只把embedding用cpu来跑，不过api跑起来了，但又提示没有GPU驱动，是否在yaml文件中还有其它的设置呢？感谢 RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx 我现在的配置如下
> 
> * acge_text_embedding:
>   alias: null # 别名
>   enable: true  # false true
>   model_name_or_path: /home/embegdding/acge_text_embedding
>   model_type: embedding
>   work_mode: hf
>   workers:
>   
>   * gpus:
>     
>     * 0

我更新了代码， 你pull 一下最新代码 再试试

**Comment by firstjack** [comment]
更新代码并修改config后依然提示没有nvidia驱动。我的yaml文件配置信息如下
`# 后台启动 nohup sh start.sh > gptserver.log &
serve_args:
  host: 0.0.0.0
  port: 8082

models:
  - chatglm3:  #自定义的模型名称
      alias: null # 别名     例如  gpt4,gpt3
      enable: false  # false true
      model_name_or_path: /home/dev/model/chatglm3-6b/
      model_type: chatglm3  # qwen  chatglm3 yi internlm
      work_mode: vllm  # vllm hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        # - 1
        - 0
      # - gpus:
      #   - 0
  
  - qwen:  #自定义的模型名称
      alias: gpt-4,gpt-3.5-turbo,gpt-3.5-turbo-16k # 别名     例如  gpt4,gpt3
      enable: false  # false true
      model_name_or_path: /home/dev/model/qwen/Qwen1___5-14B-Chat/ 
      model_type: qwen  # qwen  chatglm3 yi internlm
      work_mode: vllm  # vllm hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 1
  - yi:  #自定义的模型名称
      alias: null # 别名     例如  gpt4,gpt3
      enable: false  # false true
      model_name_or_path: /home/dev/model/01ai/Yi-34B-Chat/
      model_type: yi  # qwen  chatglm3 yi internlm
      work_mode: hf  # vllm hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 2
        # - 0

  - internlm:  #自定义的模型名称
      alias: null # 别名     例如  gpt4,gpt3
      enable: false  # false true
      model_name_or_path: /home/dev/model/Shanghai_AI_Laboratory/internlm2-chat-7b/
      model_type: internlm  # qwen  chatglm3 yi internlm
      work_mode: hf  # vllm hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 0
    
  # Embedding 模型
  - piccolo-base-zh:
      alias: null # 别名   
      enable: false  # false true
      model_name_or_path: /home/dev/model/assets/embeddings/sensenova/piccolo-base-zh/
      model_type: embedding
      work_mode: hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 2

  - bce-embedding-base_v1:
      alias: text-embedding-ada-002 # 别名   
      enable: false  # false true
      model_name_or_path: /home/dev/model/maidalun1020/bce-embedding-base_v1/
      model_type: embedding
      work_mode: hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 2

  - bce-reranker-base_v1:
      alias: null # 别名   
      enable: false  # false true
      model_name_or_path: /home/dev/model/maidalun1020/bce-reranker-base_v1/
      model_type: embedding
      work_mode: hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 0
  - bge-reranker-base:
      alias: null # 别名   
      enable: false  # false true
      model_name_or_path: /home/dev/model/Xorbits/bge-reranker-base/
      model_type: embedding
      work_mode: hf
      device: gpu  # gpu / cpu
      workers:
      - gpus:
        - 2
  
  - acge_text_embedding:
      alias: null # 别名   
      enable: true  # false true
      model_name_or_path: /home/embegdding/acge_text_embedding/
      model_type: embedding
      work_mode: hf
      device: cpu  # gpu / cpu
      workers:
      - gpus:
        - 0
`

**Comment by shell-nlp** [comment]
> 更新代码并修改config后依然提示没有nvidia驱动。我的yaml文件配置信息如下 `# 后台启动 nohup sh start.sh > gptserver.log & serve_args: host: 0.0.0.0 port: 8082
> 
> models:
> 
> * chatglm3:  #自定义的模型名称
>   alias: null # 别名     例如  gpt4,gpt3
>   enable: false  # false true
>   model_name_or_path: /home/dev/model/chatglm3-6b/
>   model_type: chatglm3  # qwen  chatglm3 yi internlm
>   work_mode: vllm  # vllm hf
>   device: gpu  # gpu / cpu
>   workers:
>   
>   * gpus:
>     # - 1
>     
>     * 0
>   
>   # - gpus:
>   # - 0
> 
> # Embedding 模型
> * acge_text_embedding:
>   alias: null # 别名
>   enable: true  # false true
>   model_name_or_path: /home/embegdding/acge_text_embedding/
>   model_type: embedding
>   work_mode: hf
>   device: cpu  # gpu / cpu
>   workers:
>   
>   * gpus:
>     
>     * 0
>       `
> 
> 后台出错信息如下 '
> 
> 2024-04-16 14:37:01 | INFO | controller | args: Namespace(host='localhost', port=21001, dispatch_method='shortest_queue', ssl=False) 2024-04-16 14:37:01 | ERROR | stderr | INFO: Started server process [2995] 2024-04-16 14:37:01 | ERROR | stderr | INFO: Waiting for application startup. 2024-04-16 14:37:01 | ERROR | stderr | INFO: Application startup complete. 2024-04-16 14:37:01 | ERROR | stderr | INFO: Uvicorn running on http://localhost:21001 (Press CTRL+C to quit) 2024-04-16 14:37:01 | INFO | openai_api_server | args: Namespace(host='0.0.0.0', port=8082, controller_address='http://localhost:21001', allow_credentials=False, allowed_origins=['_'], allowed_methods=['_'], allowed_headers=['*'], api_keys=None, ssl=False) 2024-04-16 14:37:01 | ERROR | stderr | INFO: Started server process [2996] 2024-04-16 14:37:01 | ERROR | stderr | INFO: Waiting for application startup. 2024-04-16 14:37:01 | ERROR | stderr | INFO: Application startup complete. 2024-04-16 14:37:01 | ERROR | stderr | INFO: Uvicorn running on http://0.0.0.0:8082 (Press CTRL+C to quit) 2024-04-16 14:37:05.192 | INFO | gpt_server.model_worker.base:**init**:59 - Loading the model ['acge_text_embedding'] on worker 1dd8e489 ... 2024-04-16 14:37:05 | INFO | model_worker | Register to controller 2024-04-16 14:37:05 | INFO | controller | Register a new worker: http://localhost:59126 2024-04-16 14:37:05 | INFO | controller | Register done: http://localhost:59126, {'model_names': ['acge_text_embedding'], 'speed': 1, 'queue_length': 0} 2024-04-16 14:37:05 | INFO | stdout | INFO: ::1:55760 - "POST /register_worker HTTP/1.1" 200 OK 2024-04-16 14:37:05.200 | INFO | gpt_server.model_worker.base:**init**:64 - worker 已赋值 2024-04-16 14:37:05 | INFO | sentence_transformers.SentenceTransformer | Load pretrained SentenceTransformer: /home/embegdding/acge_text_embedding/ 2024-04-16 14:37:07 | ERROR | stderr | Traceback (most recent call last): 2024-04-16 14:37:07 | ERROR | stderr | File "/home/miniconda3/envs/embedding/lib/python3.10/runpy.py", line 196, in _run_module_as_main 2024-04-16 14:37:07 | ERROR | stderr | return _run_code(code, main_globals, None, 2024-04-16 14:37:07 | ERROR | stderr | File "/home/miniconda3/envs/embedding/lib/python3.10/runpy.py", line 86, in _run_code 2024-04-16 14:37:07 | ERROR | stderr | exec(code, run_globals) 2024-04-16 14:37:07 | ERROR | stderr | File "/home/gpt_server/gpt_server/model_worker/embedding.py", line 73, in 2024-04-16 14:37:07 | ERROR | stderr | EmbeddingWorker.run() 2024-04-16 14:37:07 | ERROR | stderr | File "/home/gpt_server/gpt_server/model_worker/base.py", line 183, in run 2024-04-16 14:37:07 | ERROR | stderr | worker = cls.get_worker( 2024-04-16 14:37:07 | ERROR | stderr | File "/home/gpt_server/gpt_server/model_worker/base.py", line 147, in get_worker 2024-04-16 14:37:07 | ERROR | stderr | worker = cls( 2024-04-16 14:37:07 | ERROR | stderr | File "/home/gpt_server/gpt_server/model_worker/embedding.py", line 39, in **init** 2024-04-16 14:37:07 | ERROR | stderr | self.client = sentence_transformers.SentenceTransformer( 2024-04-16 14:37:07 | ERROR | stderr | File "/home/miniconda3/envs/embedding/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 214, in **init** 2024-04-16 14:37:07 | ERROR | stderr | self.to(device) 2024-04-16 14:37:07 | ERROR | stderr | File "/home/miniconda3/envs/embedding/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to 2024-04-16 14:37:07 | ERROR | stderr | return self._apply(convert) 2024-04-16 14:37:07 | ERROR | stderr | File "/home/miniconda3/envs/embedding/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply 2024-04-16 14:37:07 | ERROR | stderr | module._apply(fn) 2024-04-16 14:37:07 | ERROR | stderr | File "/home/miniconda3/envs/embedding/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply 2024-04-16 14:37:07 | ERROR | stderr | module._apply(fn) 2024-04-16 14:37:07 | ERROR | stderr | File "/home/miniconda3/envs/embedding/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply 2024-04-16 14:37:07 | ERROR | stderr | module._apply(fn) 2024-04-16 14:37:07 | ERROR | stderr | [Previous line repeated 1 more time] 2024-04-16 14:37:07 | ERROR | stderr | File "/home/miniconda3/envs/embedding/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply 2024-04-16 14:37:07 | ERROR | stderr | param_applied = fn(param) 2024-04-16 14:37:07 | ERROR | stderr | File "/home/miniconda3/envs/embedding/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert 2024-04-16 14:37:07 | ERROR | stderr | return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking) 2024-04-16 14:37:07 | ERROR | stderr | File "/home/miniconda3/envs/embedding/lib/python3.10/site-packages/torch/cuda/**init**.py", line 298, in _lazy_init 2024-04-16 14:37:07 | ERROR | stderr | torch._C._cuda_init() 2024-04-16 14:37:07 | ERROR | stderr | RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
> 
> '

https://github.com/shell-nlp/gpt_server/blob/fca78b2a951d6a487c6cd24d76b9e8daf9ac2ad5/gpt_server/model_worker/embedding.py#L27 发现问题了，这一行你先改成 cpu试试

**Comment by shell-nlp** [comment]
非常感谢反馈，问题已解决。 请pull 最新的代码

**Comment by shell-nlp** [comment]
你再试试 是否解决，如果解决可以关闭issue&nbsp; 如果未解决，我继续看一看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月16日(周二) 下午2:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [shell-nlp/gpt_server] 在windows下执行异常 (Issue #3)




 
更新代码并修改config后依然提示没有nvidia驱动。我的yaml文件配置信息如下
 `# 后台启动 nohup sh start.sh &gt; gptserver.log &amp;
 serve_args:
 host: 0.0.0.0
 port: 8082
 
models:
  
 
chatglm3:  #自定义的模型名称
 alias: null # 别名     例如  gpt4,gpt3
 enable: false  # false true
 model_name_or_path: /home/dev/model/chatglm3-6b/
 model_type: chatglm3  # qwen  chatglm3 yi internlm
 work_mode: vllm  # vllm hf
 device: gpu  # gpu / cpu
 workers:
  
gpus: 
- 1
  
0
  
  
- gpus:
 
- 0
 
 
 
qwen:  #自定义的模型名称
 alias: gpt-4,gpt-3.5-turbo,gpt-3.5-turbo-16k # 别名     例如  gpt4,gpt3
 enable: false  # false true
 model_name_or_path: /home/dev/model/qwen/Qwen1___5-14B-Chat/
 model_type: qwen  # qwen  chatglm3 yi internlm
 work_mode: vllm  # vllm hf
 device: gpu  # gpu / cpu
 workers:
  
gpus:  
1
  
  
 
 
yi:  #自定义的模型名称
 alias: null # 别名     例如  gpt4,gpt3
 enable: false  # false true
 model_name_or_path: /home/dev/model/01ai/Yi-34B-Chat/
 model_type: yi  # qwen  chatglm3 yi internlm
 work_mode: hf  # vllm hf
 device: gpu  # gpu / cpu
 workers:
  
gpus:  
2
  
- 0
 
  
 
 
internlm:  #自定义的模型名称
 alias: null # 别名     例如  gpt4,gpt3
 enable: false  # false true
 model_name_or_path: /home/dev/model/Shanghai_AI_Laboratory/internlm2-chat-7b/
 model_type: internlm  # qwen  chatglm3 yi internlm
 work_mode: hf  # vllm hf
 device: gpu  # gpu / cpu
 workers:
  
gpus:  
0
  
  
  
Embedding 模型
  
 
piccolo-base-zh:
 alias: null # 别名
 enable: false  # false true
 model_name_or_path: /home/dev/model/assets/embeddings/sensenova/piccolo-base-zh/
 model_type: embedding
 work_mode: hf
 device: gpu  # gpu / cpu
 workers:
  
gpus:  
2
  
  
 
 
bce-embedding-base_v1:
 alias: text-embedding-ada-002 # 别名
 enable: false  # false true
 model_name_or_path: /home/dev/model/maidalun1020/bce-embedding-base_v1/
 model_type: embedding
 work_mode: hf
 device: gpu  # gpu / cpu
 workers:
  
gpus:  
2
  
  
 
 
bce-reranker-base_v1:
 alias: null # 别名
 enable: false  # false true
 model_name_or_path: /home/dev/model/maidalun1020/bce-reranker-base_v1/
 model_type: embedding
 work_mode: hf
 device: gpu  # gpu / cpu
 workers:
  
gpus:  
0
  
  
 
 
bge-reranker-base:
 alias: null # 别名
 enable: false  # false true
 model_name_or_path: /home/dev/model/Xorbits/bge-reranker-base/
 model_type: embedding
 work_mode: hf
 device: gpu  # gpu / cpu
 workers:
  
gpus:  
2
  
  
 
 
acge_text_embedding:
 alias: null # 别名
 enable: true  # false true
 model_name_or_path: /home/embegdding/acge_text_embedding/
 model_type: embedding
 work_mode: hf
 device: cpu  # gpu / cpu
 workers:
  
gpus:  
0
 `

**Comment by firstjack** [comment]
可以了，建议能和oneapi结合一下就最好了：）

**Comment by shell-nlp** [comment]
关注点不一样，它是关注于闭源模型，而且主流闭源模型 langchain都已经支持了，开发的时候也用不到 oneapi



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月16日(周二) 晚上9:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [shell-nlp/gpt_server] 在windows下执行异常 (Issue #3)




 
可以了，建议能和oneapi结合一下就最好了：）
