### ISSUE TITLE
推理后端及接口问题（支持 tools功能 ）

### ISSUE THREAD

**Issue by 315930399** [shell-nlp/gpt_server#4]
大佬，请教下关于框架的几个问题：
1. chatcompletion接口支持传入tool吗
2. rerank、embedding支持并发推理吗
3. 有没有接口文档，fastapi自带的那种

**Comment by shell-nlp** [comment]
> 大佬，请教下关于框架的几个问题：
> 
> 1. chatcompletion接口支持传入tool吗
> 2. rerank、embedding支持并发推理吗
> 3. 有没有接口文档，fastapi自带的那种

1. 不支持传入 tool  因为传入tool 说明 这个工具以及被实现，但是开发过程中，tool是自定义，完全可以使用 langchain 自行实现
2. rerank embedding 响应都很快， 即使不支持并发，QPS也是很高的。 如果还觉得QPS低，可以多启动几个 worker
3. 有的，项目是用fastapi实现，完全可以使用  ip：port/docs 查看openai文档

**Comment by 315930399** [comment]
> > 大佬，请教下关于框架的几个问题：
> > 
> > 1. chatcompletion接口支持传入tool吗
> > 2. rerank、embedding支持并发推理吗
> > 3. 有没有接口文档，fastapi自带的那种
> 
> 1. 不支持传入 tool  因为传入tool 说明 这个工具以及被实现，但是开发过程中，tool是自定义，完全可以使用 langchain 自行实现
> 2. rerank embedding 响应都很快， 即使不支持并发，QPS也是很高的。 如果还觉得QPS低，可以多启动几个 worker
> 3. 有的，项目是用fastapi实现，完全可以使用  ip：port/docs 查看openai文档

没有tool字段的话，怎么使用langchain的bind_tool呢

**Comment by shell-nlp** [comment]
> 大佬，请教下关于框架的几个问题：
> 
> 1. chatcompletion接口支持传入tool吗
> 2. rerank、embedding支持并发推理吗
> 3. 有没有接口文档，fastapi自带的那种

近期我将测试 tools 的功能，请持续关注

**Comment by shell-nlp** [comment]
> 大佬，请教下关于框架的几个问题：
> 
> 1. chatcompletion接口支持传入tool吗
> 2. rerank、embedding支持并发推理吗
> 3. 有没有接口文档，fastapi自带的那种

qwen glm4 已经支持 langchain的 bind_tools功能  你可以试试
