### ISSUE TITLE
rerank模型能否支持 http://ip:8082/v1/rerank 调用？

### ISSUE THREAD

**Issue by edisonzf2020** [shell-nlp/gpt_server#6]
cohere 的rerank调用是通过 "POST /v1/rerank HTTP/1.1"  这样的请求，Jina也是，能否api也能支持这个规范？

**Comment by shell-nlp** [comment]
这种规范有什么好处，可以兼容什么框架，我不是很了解，如果有兼容的框架的话，我后面可以修改一下接口。

---原始邮件---
发件人: "Anne ***@***.***&gt;
发送时间: 2024年5月13日(周一) 晚上10:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [shell-nlp/gpt_server] rerank模型能否支持 http://ip:8082/v1/rerank 调用？ (Issue #6)




 
cohere 的rerank调用是通过 "POST /v1/rerank HTTP/1.1"  这样的请求，Jina也是，能否api也能支持这个规范？

**Comment by edisonzf2020** [comment]
是的，现在各家的rerank模型的api都兼容Cohere的rerank框架，https://docs.cohere.com/reference/rerank
您看下是否有帮助

**Comment by shell-nlp** [comment]
> 是的，现在各家的rerank模型的api都兼容Cohere的rerank框架，https://docs.cohere.com/reference/rerank 您看下是否有帮助

因为我实现的 兼容 openai的格式，而非Cohere 库的接口，因此 你使用的话，建议还是用我这种方式。（虽然rerank openai 官方还没实现）

**Comment by shell-nlp** [comment]
> cohere 的rerank调用是通过 "POST /v1/rerank HTTP/1.1" 这样的请求，Jina也是，能否api也能支持这个规范？

已经实现，请体验    https://github.com/shell-nlp/gpt_server/blob/main/tests/test_rerank.py
