### ISSUE TITLE
【求助】构建镜像出错

### ISSUE THREAD

**Issue by taurusduan** [shell-nlp/gpt_server#7]
root@debiandocker build -t gpt_server:v0.2.1 .
[+] Building 0.7s (8/8) FINISHED                                                      docker:default
 => [internal] load build definition from Dockerfile                                            0.0s
 => => transferring dockerfile: 674B                                                            0.0s
 => [internal] load metadata for docker.io/continuumio/miniconda3:main                          0.0s
 => [internal] load .dockerignore                                                               0.0s
 => => transferring context: 88B                                                                0.0s
 => [internal] load build context                                                               0.0s
 => => transferring context: 31.27kB                                                            0.0s
 => [1/4] FROM docker.io/continuumio/miniconda3:main                                            0.0s
 => CACHED [2/4] COPY ./ /gpt_server                                                            0.0s
 => CACHED [3/4] WORKDIR /gpt_server                                                            0.0s
 => ERROR [4/4] RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list &&    0.6s
------                                                                                               
 > [4/4] RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list &&     sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list &&     pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple &&     conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ &&     conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ &&     conda config --set show_channel_urls yes &&     pip install -r requirements.txt  && pip cache purge:
0.496 sed: can't read /etc/apt/sources.list: No such file or directory
------
Dockerfile:7
--------------------
   6 |     
   7 | >>> RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
   8 | >>>     sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
   9 | >>>     pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple && \
  10 | >>>     conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ && \
  11 | >>>     conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ && \
  12 | >>>     conda config --set show_channel_urls yes && \
  13 | >>>     pip install -r requirements.txt  && pip cache purge
  14 |     CMD ["/bin/bash"]
--------------------
ERROR: failed to solve: process "/bin/sh -c sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list &&     sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list &&     pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple &&     conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ &&     conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ &&     conda config --set show_channel_urls yes &&     pip install -r requirements.txt  && pip cache purge" did not complete successfully: exit code: 2
root@debian:/mnt/gpt_server-api#

**Comment by shell-nlp** [comment]
构建镜像的步骤我还没有进行整理，仓库中的dockerfile 是我自用的，你直接使用的话肯定会报错的，后面有时间我会整理一个构建镜像的一个正确的dockerfile 并修改readme，你可以先本地启动暂时先用，或者自己探索一下怎么构建.

**Comment by taurusduan** [comment]
> 构建镜像的步骤我还没有进行整理，仓库中的dockerfile 是我自用的，你直接使用的话肯定会报错的，后面有时间我会整理一个构建镜像的一个正确的dockerfile 并修改readme，你可以先本地启动暂时先用，或者自己探索一下怎么构建.

原来如此，谢谢啊。

**Comment by shell-nlp** [comment]
> > 构建镜像的步骤我还没有进行整理，仓库中的dockerfile 是我自用的，你直接使用的话肯定会报错的，后面有时间我会整理一个构建镜像的一个正确的dockerfile 并修改readme，你可以先本地启动暂时先用，或者自己探索一下怎么构建.
> 
> 原来如此，谢谢啊。

现在你可以尝试使用dockerfile构建，教程已经再readme 提供， 可以测试一下 行不行

**Comment by taurusduan** [comment]
> > > 构建镜像的步骤我还没有进行整理，仓库中的dockerfile 是我自用的，你直接使用的话肯定会报错的，后面有时间我会整理一个构建镜像的一个正确的dockerfile 并修改readme，你可以先本地启动暂时先用，或者自己探索一下怎么构建.
> > 
> > 
> > 原来如此，谢谢啊。
> 
> 现在你可以尝试使用dockerfile构建，教程已经再readme 提供， 可以测试一下 行不行

好的，我试试啊

**Comment by shell-nlp** [comment]
请问是否构建成功

**Comment by taurusduan** [comment]
> 请问是否构建成功

抱歉啊，我这几天正在忙着录入知识库。第一次构建失败了，我这边用的是baichuan2-7b的模型，还没来得及检查。我这边下个星期四才能搞定，才有时间弄这个。

**Comment by shell-nlp** [comment]
> > 请问是否构建成功
> 
> 抱歉啊，我这几天正在忙着录入知识库。第一次构建失败了，我这边用的是baichuan2-7b的模型，还没来得及检查。我这边下个星期四才能搞定，才有时间弄这个。

baichuan2我还没支持，我支持一下baichuan2

**Comment by shell-nlp** [comment]
> > 请问是否构建成功
> 
> 抱歉啊，我这几天正在忙着录入知识库。第一次构建失败了，我这边用的是baichuan2-7b的模型，还没来得及检查。我这边下个星期四才能搞定，才有时间弄这个。

现在已经支持 baichuan2 了

**Comment by shell-nlp** [comment]
> ## root@debiandocker build -t gpt_server:v0.2.1 .
> [+] Building 0.7s (8/8) FINISHED docker:default
> => [internal] load build definition from Dockerfile 0.0s
> => => transferring dockerfile: 674B 0.0s
> => [internal] load metadata for docker.io/continuumio/miniconda3:main 0.0s
> => [internal] load .dockerignore 0.0s
> => => transferring context: 88B 0.0s
> => [internal] load build context 0.0s
> => => transferring context: 31.27kB 0.0s
> => [1/4] FROM docker.io/continuumio/miniconda3:main 0.0s
> => CACHED [2/4] COPY ./ /gpt_server 0.0s
> => CACHED [3/4] WORKDIR /gpt_server 0.0s
> => ERROR [4/4] RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && 0.6s
> > [4/4] RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list &&     sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list &&     pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple &&     conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ &&     conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ &&     conda config --set show_channel_urls yes &&     pip install -r requirements.txt  && pip cache purge:
> > 0.496 sed: can't read /etc/apt/sources.list: No such file or directory
> 
> ## Dockerfile:7
> ## 6 |
> 7 | >>> RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list &&
> 8 | >>> sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list &&
> 9 | >>> pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple &&
> 10 | >>> conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ &&
> 11 | >>> conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ &&
> 12 | >>> conda config --set show_channel_urls yes &&
> 13 | >>> pip install -r requirements.txt && pip cache purge
> 14 | CMD ["/bin/bash"]
> ERROR: failed to solve: process "/bin/sh -c sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple && conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ && conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ && conda config --set show_channel_urls yes && pip install -r requirements.txt && pip cache purge" did not complete successfully: exit code: 2 root@debian:/mnt/gpt_server-api#

我构建的镜像已经上传到 dockerhub 请尝试
```bash
docker pull 506610466/gpt_server:latest # 如果拉取失败可尝试下面的方式


# 如果国内无法拉取docker镜像，可以尝试下面的国内镜像拉取的方式（不保证国内镜像源一直可用）
docker pull docker.rainbond.cc/506610466/gpt_server:latest 
```

**Comment by taurusduan** [comment]
> > ## root@debiandocker build -t gpt_server:v0.2.1 .
> > [+] Building 0.7s (8/8) FINISHED docker:default
> > => [internal] load build definition from Dockerfile 0.0s
> > => => transferring dockerfile: 674B 0.0s
> > => [internal] load metadata for docker.io/continuumio/miniconda3:main 0.0s
> > => [internal] load .dockerignore 0.0s
> > => => transferring context: 88B 0.0s
> > => [internal] load build context 0.0s
> > => => transferring context: 31.27kB 0.0s
> > => [1/4] FROM docker.io/continuumio/miniconda3:main 0.0s
> > => CACHED [2/4] COPY ./ /gpt_server 0.0s
> > => CACHED [3/4] WORKDIR /gpt_server 0.0s
> > => ERROR [4/4] RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && 0.6s
> > > [4/4] RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list &&     sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list &&     pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple &&     conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ &&     conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ &&     conda config --set show_channel_urls yes &&     pip install -r requirements.txt  && pip cache purge:
> > > 0.496 sed: can't read /etc/apt/sources.list: No such file or directory
> > 
> > 
> > ## Dockerfile:7
> > ## 6 |
> > 7 | >>> RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list &&
> > 8 | >>> sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list &&
> > 9 | >>> pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple &&
> > 10 | >>> conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ &&
> > 11 | >>> conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ &&
> > 12 | >>> conda config --set show_channel_urls yes &&
> > 13 | >>> pip install -r requirements.txt && pip cache purge
> > 14 | CMD ["/bin/bash"]
> > ERROR: failed to solve: process "/bin/sh -c sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple && conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ && conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ && conda config --set show_channel_urls yes && pip install -r requirements.txt && pip cache purge" did not complete successfully: exit code: 2 root@debian:/mnt/gpt_server-api#
> 
> 我构建的镜像已经上传到 dockerhub 请尝试
> 
> ```shell
> docker pull 506610466/gpt_server:latest # 如果拉取失败可尝试下面的方式
> 
> 
> # 如果国内无法拉取docker镜像，可以尝试下面的国内镜像拉取的方式（不保证国内镜像源一直可用）
> docker pull docker.rainbond.cc/506610466/gpt_server:latest 
> ```

好的，谢谢啊大佬。我开了个新的请教一下其他的
